### ISSUE TITLE
hi, (  exists (a|b|c|d)  ) && ( !exists (e|f|g) )

### ISSUE THREAD

**Issue by xuwuo** [zouzias/spark-lucenerdd#104]

**Comment by zouzias** [comment]
Hi there,

Can you elaborate a bit your question?

Wild guess: If you want to do the above query you need to rewrite as a Lucene Query, see https://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/QueryParser.html

which is something like `fieldName: ( a OR b OR c OR d AND NOT (e OR f OR g)` (untested)

**Comment by xuwuo** [comment]
thank you.
