### ISSUE TITLE
DataFrame to LuceneRDD

### ISSUE THREAD

**Issue by thangarajan8** [zouzias/spark-lucenerdd#105]
Currently i am able to convert a DataFrame to LuceneRDD but while queering i not getting any thing.
Scehma of the RDD

> root
>  |-- ID: integer (nullable = false)
>  |-- Name: string (nullable = false)
>  |-- CountryCode: string (nullable = false)
>  |-- District: string (nullable = false)
>  |-- Population: integer (nullable = false)

Example Record : [1,Kabul,AFG,Kabol,1780000]
Scala Code:
```javascript
luceneRDD.termQuery("name","Kabul",1)
  ```
Can anyone help me

**Comment by zouzias** [comment]
Hi there,

Which version of LuceneRDD are you using? The issue might be that the query analyzer does not lowercase your query. If you use version 0.2.7, it should be good.

Can you try (lowercase the query)

```
luceneRDD.termQuery("name","kabul",1)
```

and / or

```
luceneRDD.query("name:kabul",1)
 ```

Let me know if it helps.

**Comment by thangarajan8** [comment]
Yes, Now it is working Thanks for Fast Reply
