### ISSUE TITLE
 pattern match for suffix

### ISSUE THREAD

**Issue by Velmuruganms12** [zouzias/spark-lucenerdd#106]
can we  try same code with pattern match for suffix or something like regular exp. Any one has tried different option pls let me know.

**Comment by zouzias** [comment]
Hi there,

The reverse string filter (https://lucene.apache.org/core/5_4_0/analyzers-common/index.html?org/apache/lucene/analysis/reverse/ReverseStringFilter.html) is not supported yet.Hence, for the suffix part of your question, you can reduce it to a prefix query as follow.

At index time, you reverse your input tokens (be careful with stemming etc here). Then, do the same at query time, i.e.,

```
val input = Array("town", "city")
val suffixQuery = "ty"
```

reverse them to `ytic`, `nwot` before instantiating the LuceneRDD and then at query do, `LuceneRDD.query("_1:yt*")`

I would suggest to add an extra field, i.e., `fieldName_reverse` where you follow this logic for all fields that you need to do suffix queries.

**Comment by zouzias** [comment]
For some examples of prefix / fuzzy etc query take a look at the tests: 

https://github.com/zouzias/spark-lucenerdd/blob/master/src/test/scala/org/zouzias/spark/lucenerdd/LuceneRDDSearchSpec.scala
