### ISSUE TITLE
Recommendation: Naming Persisted/Cached RDDs

### ISSUE THREAD

**Issue by dutrow** [zouzias/spark-lucenerdd#111]
After integrating LuceneRDD into our Spark application, I noticed a bunch of unnamed MapPartitionsRDD showing up in the sparkmaster:4040/storage webpage.  There are several places in this codebase where rdd.persist(StorageLevel) is called without doing something like rdd.name = "LuceneRDDResponse" to make it more clear about what RDDs are contributing to stored. It looks like you have a setName method on LuceneRDD that could be easily extended to other RDDs in your library.

**Comment by zouzias** [comment]
Thank you for the recommendation @dutrow . It is a good point.

I will push the fix on 0.2.9-SNAPSHOT artifacts tonight in case you need this feature.

**Comment by dutrow** [comment]
Great, thanks for the update!
