### ISSUE TITLE
How much index size is supported?

### ISSUE THREAD

**Issue by sjcheng** [zouzias/spark-lucenerdd#119]
Hi all,

I would like to use that, and want to know how much index size is supported by spark-lucenerdd? Could it support million size documents ? I saw the default config of index store is using memory, while our index size seems cannot load to memory once.

Thanks
Aimee

**Comment by zouzias** [comment]
Hi Aimee,

The index can be stored in the executor's memory or on each executors disk. You can change the behavior using the parameter `lucenerdd.index.store.mode={disk|memory}`

For a spark submit example, see https://github.com/zouzias/spark-lucenerdd-aws/blob/master/spark-submit.sh#L30

I have tried examples with millions of documents and I didn't have any issues. Let me know if you experience any issues and I would be happy to help.

**Comment by sjcheng** [comment]
Another question, how many queries can supported in one job and how about the query speed ? We used tried elephant-bird's pig-lucene which combine the lucene index and search in hdfs, but when we search many queries in a time, will meet memory problem.

**Comment by zouzias** [comment]
If the number of queries is relatively small, you can collect them in the driver and do the queries as in 

https://github.com/zouzias/spark-lucenerdd-aws/blob/master/src/main/scala/org/zouzias/spark/lucenerdd/aws/search/wikipedia/WikipediaSearchExample.scala

If not, you can batch your queries in an RDD and get back the results as an `RDD[QueryIdType, TopKResults]` using `LuceneRDD.link`

An example for the latter case is documented here: https://github.com/zouzias/spark-lucenerdd/wiki/Record-Linkage

For the latter case, I have some preliminary timings at http://www.slideshare.net/zouzias/lucenerdd-for-geospatial-search-and-entity-linkage (see the linkage slide)

**Comment by sjcheng** [comment]
Thanks for you replying! 

For the first case, how many Wikipedia documents put in the index when you do the example ? 

And the link "http://www.slideshare.net/zouzias/lucenerdd-for-geospatial-search-and-entity-linkage" shows  "The file link that you requested is not valid.", could you check that or could you send to me directly?

**Comment by zouzias** [comment]
Hi,

These are all the *titles* of all english wikipedia articles, it is about 1-10 million documents.

The link works here. If not, you can go on https://www.slideshare.net and search for lucenerdd.
