### ISSUE TITLE
Use to process data using a pre-existing Lucene index

### ISSUE THREAD

**Issue by darrenhaken** [zouzias/spark-lucenerdd#130]
I have a Lucene index which I'd like to use to process a large corpus of data with.

Is it possible with this library to load in a prebuilt Lucene index and then process the data against it?

**Comment by zouzias** [comment]
Hi,

LuceneRDD will not help you in this scenario. However, if you do have the data that created the prebuilt  Lucene index, then LuceneRDD might be of help. You can create a "sharded" Lucene index on which you can process your large corpus data with.
