### ISSUE TITLE
Can I do full text search without indicating filed name in phrase query?

### ISSUE THREAD

**Issue by darouwan** [zouzias/spark-lucenerdd#135]
In phrase search, it needs me to specify a field name. But in practice I have a lot of  columns and searching each field one by one seems not convenient. Does it support to do search without specifying field?

**Comment by zouzias** [comment]
As far as I remember, Lucene query syntax allows you to specify all fields using a wildcard `"*:\"my phrase query\"" `.

If this doesn't work, you can programmatically generate your Lucene Query String, but using the `.fields()` method. For example, something like the following should work (untested)

```
val flds = luceneRDD.fields()
val lqs = flds.map(x => x + s":\"${phraseQuery}\"").mkString(" OR ")

val response = luceneRDD.query(lqs)
```
