### ISSUE TITLE
How to persist the indexed data and use it in later time?

### ISSUE THREAD

**Issue by darouwan** [zouzias/spark-lucenerdd#136]
As create index for massive data cost a lot of time, it is reasonable to persist indexed data and search with it in later time. 

I have tried to save luceneRDD as textfile, but it seems not containing index data. 

So how to persist it?

**Comment by zouzias** [comment]
You need to do "luceneRDD.cache()" so that the indexed data are persisted.

**Comment by zouzias** [comment]
Yes, exactly. This will force spark to index the data only once.

JF Chen <notifications@github.com> schrieb am Do., 10. Mai 2018, 03:21:
