### ISSUE TITLE
java.lang.NoSuchMethodError for 

### ISSUE THREAD

**Issue by pmaditya** [zouzias/spark-lucenerdd#152]
**Describe the bug**
I am getting the following error when I am running the code.
java.lang.NoSuchMethodError: org.apache.lucene.index.MultiFields.getTermPositionsEnum(Lorg/apache/lucene/index/IndexReader;Ljava/lang/String;Lorg/apache/lucene/util/BytesRef;I)Lorg/apache/lucene/index/PostingsEnum;
	at org.apache.lucene.facet.taxonomy.directory.TaxonomyIndexArrays.initParents(TaxonomyIndexArrays.java:131)
	at org.apache.lucene.facet.taxonomy.directory.TaxonomyIndexArrays.<init>(TaxonomyIndexArrays.java:55)
	at org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyWriter.getTaxoArrays(DirectoryTaxonomyWriter.java:732)
	at org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyWriter.addCategoryDocument(DirectoryTaxonomyWriter.java:503)
	at 

**To Reproduce**
code : 
val array = Array("Hello", "world")
    val rdd = LuceneRDD(array)
    val result = rdd.termQuery("_1", "hello", 10)
    result.foreach(println)

MVN Version : 2.8

Spark Version : 2.2

**Expected behavior**

**Versions (please complete the following information):**
 - spark-lucenerdd version: [e.g. 0.2.9.]
 - Spark Version: [e.g. 2.2]
 - Java version: [e.g. Java 8]

**Additional context**

**Comment by zouzias** [comment]
Can you update to spark-lucenerdd version `0.3.5` and report back?

See here for a simple example: https://github.com/zouzias/spark-lucenerdd-examples/blob/master/src/main/scala/org/zouzias/spark/lucenerdd/examples/wikipedia/CapitalsSearchExample.scala

**Comment by yeikel** [comment]
I saw this error before when I had two different versions of Lucene in my classpath. Make sure this is not the case

**Comment by yeikel** [comment]
@ pmaditya Did you resolve this issue. Please let us know if it is okay to close this

**Comment by pmaditya** [comment]
@yeikel You are right. There are two versions of Lucene libraries in my workspace and the other library is causing the issue. This issue can be closed.
