### ISSUE TITLE
Question about blockEntityLinkage

### ISSUE THREAD

**Issue by yeikel** [zouzias/spark-lucenerdd#153]
I have a question about the following line : 

```
 val linkedResults = LuceneRDD.blockEntityLinkage(a, b,
      linker,
      Array("blocker"),
      Array("blocker"),
      500
    )
```

How will it link **a** and **b**?  

a ) Search for all the entries of **a** in **b**  , 
b) All the entries of **b** in **a**
c) combine a and b and search both? 

Ideally , I'd like to archive the option b) , where I have a small table **"b"** that I'd like to link with a larger table **"a"**

Thank you.

**Comment by zouzias** [comment]
The semantics of the block linkage is as follows:

1. Split a and b into blocks based on the value on column "blocker". Say a value of the blocker column is "blocker_value_1".
2. Then, approximate link all values between *a* and *b* that have value on column "blocker" equal to *exactly* "blocker_value_1".

You could use blocking on any column where you know that *a* and *b* have common values and you can assume that you can condition on such a column.

See Slide 15 here: http://helios.mi.parisdescartes.fr/~themisp/publications/PapadakisPalpanas-TutorialWWW2018.pdf

**Comment by yeikel** [comment]
Thank you for your answer @zouzias , but it is still not clear to me. 

Given that I have a small dataset B that I'd like to link to a bigger dataset A , how can I do this link using a custom linker(query)?

**Comment by zouzias** [comment]
For block dedup here is an example that is working: https://github.com/zouzias/spark-lucenerdd-examples/blob/develop/src/main/scala/org/zouzias/spark/lucenerdd/examples/linkage/BlockDedupAmazon.scala

Using `0.3.6-SNAPSHOT`, what you need to do is something like:

```
val A = spark.read.XXX
val B = spark.read.XXX

    // Custom linker
    val linker: Row => Query = { row => {
        val name = row.getString(row.fieldIndex("name"))

        val booleanQuery = new BooleanQuery.Builder()

        if (!name.isEmpty){
            booleanQuery.add(new FuzzyQuery(new Term("name", name)), Occur.SHOULD)
           booleanQuery.build()
        }
        else {
          new MatchAllDocsQuery()
        }
      }
    }

    val blockingFields = Array("country")

    // Block entity linkage
    val linkedResults = LuceneRDD.blockEntityLinkage(B, A, linker,  blockingFields, blockingFields)
```

Order of A and B is important.

**Comment by yeikel** [comment]
How can I set the top K matches for this? 

`    val linkedResults = LuceneRDD.blockEntityLinkage(B, A, linker,  blockingFields, blockingFields)
`

**Comment by zouzias** [comment]
You can do:
```
val topK = 5
val linkedResults = LuceneRDD.blockEntityLinkage(B, A, linker, blockingFields, blockingFields, topK)
```

**Comment by yeikel** [comment]
If I don't set K I assume it will find all the results that meet the liker. Is that assumption correct?

**Comment by zouzias** [comment]
Default K equals 3.

**Comment by yeikel** [comment]
That works. 

Thank you for your explanation and the paper you shared. 

Any other presentation or lecture about the topic is welcome. 

Thank you!

**Comment by yeikel** [comment]
Is there any similar linker that does not take any blockers? 

For example , 

Search all the elements of B in A
