### ISSUE TITLE
Remove dependency on sbt-spark-package

### ISSUE THREAD

**Issue by zouzias** [zouzias/spark-lucenerdd#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
* https://github.com/databricks/sbt-spark-package/issues/48
* https://github.com/databricks/sbt-spark-package/pull/41

**Comment by yeikel** [comment]
What is the alternative?

**Comment by zouzias** [comment]
There is no need to use this plugin and more, since it does not provide any extra functionality. sbt-spark-package gives a bit more easy-handling in the setup of sbt but it could be removed safely.
