### ISSUE TITLE
[question]want to knnSearch on for every record from other data frame - 

### ISSUE THREAD

**Issue by narendrasfo** [zouzias/spark-lucenerdd#186]
Hi ,

I have one large data frame that  has latitude and longitude and other data set has some 1 million records, how can i use   knnSearch for my large data set where i want to get n near lat,long for each lat , long

val bigdf= data[100 ml rows] // need to calculate knn (n) here for each latt,long 
val dict = dict // it has lat,long
\for exp : bigdf.withColumn("1-nearest",do something here<want to use here your rdd>)

**Comment by zouzias** [comment]
There is an example for radius based linkage here which might be related to your question: 

https://github.com/zouzias/spark-lucenerdd-examples/blob/develop/src/main/scala/org/zouzias/spark/lucenerdd/examples/linkage/shape/ShapeLuceneRDDLinkageCountriesvsCapitals.scala

The above example performs a linkage between `countries` as multipoligons versus `capitals` as (x,y) points.
