### ISSUE TITLE
Weird results when running it distributed vs local

### ISSUE THREAD

**Issue by yeikel** [zouzias/spark-lucenerdd#227]
I am not sure what the issue is , but when I execute the project in my cluster , the documents that are being matched do not seem to be related to the query I am running. I am not sure why this is happening because when I execute the project locally , it is producing the desired results. 

If it helps , I am running the modified version posted [here](https://github.com/zouzias/spark-lucenerdd/pull/162) 

    val data = spark
      .read
      .format("csv")
      .option("header", "true")
      .option("delimiter", "\u0001")
      .load("path")
      .select("address")
      .where("address is not null AND address != ''")
      .dropDuplicates("address")
      .repartition(2)

    val index = LuceneRDD(data)

    val linkedResults = index.link(data.rdd, linker, 10000).filter(_._2.nonEmpty)

    val linkageResults = spark.createDataFrame(linkedResults.map { case (original, topDocs) =>
      val originalName = original.getString(original.fieldIndex("address"))
      val documentName = topDocs
        .map(d => d.getString(topDocs.head.fieldIndex("address")))
        .filter(s=> !originalName.equals(s))
      (originalName, documentName)
    }).toDF("originalAdd", "candidates")
    .filter(size($"candidates") > 0)

```
val linker: Row => Query = row => {

      def analyze(text: String): Array[String] = {

        val analyzer = new StandardAnalyzer()
        val result = mutable.ArrayBuilder.make[String]()
        val tokenStream = analyzer.tokenStream("text", text)
        val attr = tokenStream.addAttribute(classOf[CharTermAttribute])
        tokenStream.reset()
        while (tokenStream.incrementToken()) {
          result.+=(attr.toString)
        }
        result.result()
      }

      def minShouldMatch(tokens: Seq[String]): Integer = {

        def roundUp(d: Double) = math.ceil(d).toInt

        if (tokens.length <= 3) {
          tokens.length
        } else {
          roundUp(tokens.length * 0.8)
        }
      }

      val address = row.getString(row.fieldIndex("address"))

      val addQuery = new BooleanQuery.Builder()

      val tokens: Seq[String] = analyze(address).filter(_.length >= 2)

      tokens.foreach { nameToken =>
        addQuery.add(new TermQuery(new Term("address", nameToken)), Occur.SHOULD)
      }

      addQuery.setMinimumNumberShouldMatch(minShouldMatch(tokens))

      addQuery.build()
    }
```
When I execute that code locally , I get the following results(expected and desired) : 

```
{
  "originalAdd": "4006 WILLOW PASS RD APT H CONCORD CA US",
  "candidates": [
    "4006 WILLOW PASS RD APT C CONCORD CA US"
  ]
}
```

But when I execute it on my cluster , results are very different

```
"originalAdd": "58 FOXALL RD NORTH KELLYVILLE NSW 2155 AU",
  "candidates": [
    "SOLER Y PALAU SA DE CV BLVD A NUM 15 COL PQUE IND PUEBLA 2000 MEXICO 72310 MX",
    "10 RUE PADDON NOUMEA 98800 NC",
    "14 RUE LE CARROUR OUEMO NOUMEA 98800 NC"
  ]
```
If we look at the query , the documents above should not match at all as they don't share any token in common.

Any tip would be appreciated. 

Thanks!

**Comment by zouzias** [comment]
How is the following example behave in cluster mode?

```
{
  "originalAdd": "4006 WILLOW PASS RD APT H CONCORD CA US",
  "candidates": [
    "4006 WILLOW PASS RD APT C CONCORD CA US"
  ]
}
```

Do you still get the same result as in local mode?

**Comment by yeikel** [comment]
I believe I identified the issue. 

In a few words , this filter : 

`      val tokens: Seq[String] = analyze(address).filter(_.length >= 2)
`

Was generating an empty Seq of tokens which then translated into an empty query 

`addQuery.build() `

Which meant that it was basically pulling anything. 

I added a guard to return an empty set of documents if the query is empty in order to avoid this issue. Please let me know if you think there is a better way to do this. 

```
def searchQuery(indexSearcher: IndexSearcher,
                  query: Query,
                  topK: Int)
  : Seq[SparkScoreDoc] = {

     if (query.toString.equalsIgnoreCase("")) {
       Seq()
     }else{
       indexSearcher.search(query, topK).scoreDocs.map(SparkScoreDoc(indexSearcher, _))
     }
  }
```


Is there any situation where we'd like to link on all? 

I saw that in a couple of [your examples](https://github.com/zouzias/spark-lucenerdd-examples/blob/master/src/main/scala/org/zouzias/spark/lucenerdd/examples/linkage/LinkageGooglevsAmazon.scala#L70) : 

```
 if (nameTokens.nonEmpty) {
          s"_2:(${nameTokens})"
        }
        else {
          "*:*"
        }
```

Thanks for your help!

**Comment by zouzias** [comment]
You are free to choose the linkage logic in the link function. The only requirement is that you need to have a valid Lucene query. In the spark-lucenerdd examples, I use a `*:*` match all query for the cases where I cannot construct a query (randomly linkage).

Depending your use case, you can use `*:<A NON EXISTENT TERM>` to return zero result if you don't want to return random results.

**Comment by zouzias** [comment]
I guess there is no issue in distributed vs local execution, so closing the issue. Feel free to reopen the issue.

**Comment by yeikel** [comment]
That's correct. I don't there is any issue. I just got confused with the empty query. 

 What is the general use case where a user would like to get random linkages? 

I imagine that running `*:<A NON EXISTENT TERM>` will still execute the query in Lucene so that would be a little waste of time
