### ISSUE TITLE
How to search with lucenerdd in another queries' rdd?

### ISSUE THREAD

**Issue by HITlilingzhi** [zouzias/spark-lucenerdd#263]
Thanks a lot for your tool honstly! I have tons of queries in one rdd and want to search every query in it with a luceneRdd. like this:

```
val lucenenRdd = LuceneRDD(some index content.rdd)
queries.map(
  x => lucenenRdd.query(x, 100)
)
// queries is another rdd with tons of queries
```

But it has the error that I cannot call rdd1 in rdd2, error message:

```
Caused by: org.apache.spark.SparkException: This RDD lacks a SparkContext. It could happen in the following cases:
(1) RDD transformations and actions are NOT invoked by the driver, but inside of other transformations; for example, rdd1.map(x => rdd2.values.count() * x) is invalid because the values transformation and count action cannot be performed inside of the rdd1.map transformation. For more information, see SPARK-5063.
(2) When a Spark Streaming job recovers from checkpoint, this exception will be hit if a reference to an RDD not defined by the streaming job is used in DStream operations. For more information, See SPARK-13758.
```

I try to broadcast lucenenRdd, which requires using collect() function to convert to an Array[] firstly, and then I can broadcast successfully. But after collect(), I got an Array[] and loss the query/termQuery/fuzzyQuery function.

So could you tell me what can I do to handle this problem?

Thanks Again!

**Comment by zouzias** [comment]
Hi there,

The problem in your code snippet is that you are not allowed to have an RDD object within an `RDD.map()` method. In your example, `luceneRDD` is an RDD.

You should use the `link` method of LuceneRDD where you will link luneneRDD with your queries. See for example:

https://github.com/zouzias/spark-lucenerdd-examples/blob/develop/src/main/scala/org/zouzias/spark/lucenerdd/examples/linkage/LinkageScholarvsDBLP.scala

See also the slides (slide 23+): https://www.slideshare.net/zouzias/lucenerdd-for-geospatial-search-and-entity-linkage for an explanation on what is happening under the hood.
