### ISSUE TITLE
Spark 3.4.1 no longer ships slf4j

### ISSUE THREAD

**Issue by robvadai** [zouzias/spark-lucenerdd#481]
**Describe the bug**

Compiler issue with Spark 3.4:

```
import org.slf4j.impl.StaticLoggerBinder
```

**To Reproduce**

Build it, in my case using Gradle

**Expected behavior**

Use internal Spark logging

in 

```
org.zouzias.spark.lucenerdd.analyzers.AnalyzerConfigurable
org.zouzias.spark.lucenerdd.store.IndexStorable
```

just use

```
import org.apache.spark.internal.Logging
```

**Versions (please complete the following information):**
 - spark-lucenerdd version: master branch
 - SBT version: I used Gradle
 - Spark Version: 3.4.1
 - Java version: 11

**Comment by zouzias** [comment]
Hey @robvadai , thanks for pointing this out.

I made a PR that I think solves your concern. Can you take a look and let me know if it looks good?

If all is good, I will bump the Spark version to 3.4.1 and release a snapshot of the library.
