### ISSUE TITLE
Questions about query results

### ISSUE THREAD

**Issue by wuxianxingkong** [zouzias/spark-lucenerdd#81]
I read your github project spark-lucenerdd, it's great and the code is elegant. I have a question about LuceneRDD.*query().collect(), are the results from collect function global top K ?  For example, when we index on a DataSet which consists of  several paritions, and every partitions will be processed and store lucene index, after that, we do search from different paritions' index and collect them. Is it the right way that the query result from different partitions sorted by their score(Because I think that inverted list is not overall ). Please forgive me if there is any mis-understanding ! (My english is not very good , but i am working on it O(∩_∩)O). Thanks!

**Comment by zouzias** [comment]
Hi there,

For a high level description of the internals, you can take a look at a presentation that I gave a few weeks ago:

http://www.slideshare.net/zouzias/lucenerdd-for-geospatial-search-and-entity-linkage

Yes, the LuceneRDD.query should return the topK results similar to what a Solr Cloud or Elasticsearch cluster will do. The inverted index is not over all the documents but only local per partition. Hence, the global TF-IDF of a single index is not the same with TF-IDF of a partition set of indices. Note that the same is true with Elasticsearch / Solr Cloud (to the best of my knowledge).

That said, this is the price to pay when you move from a single index to a set of distributed indices. The assumption is that as the number of documents increasing (and # of partitions is fixed), the TF-IDF scores will be a good approximation to the global TF-IDF.

You can check the influence of the above TF-IDF approximation on your dataset by repartitioning / reordering your data and checking the changes on the topK results.

If you think there is an easy fix to this issue, I would be happy to include it into the codebase.

**Comment by zouzias** [comment]
See also http://stackoverflow.com/questions/21529573/solr-cloud-effect-of-tf-idf-on-querying-with-multiple-shards

**Comment by wuxianxingkong** [comment]
I am sorry to get back to you late. Thanks for your detailed answer. I will try to check it on some data sets.
