### ISSUE TITLE
Error when attempting to run example

### ISSUE THREAD

**Issue by dom9988** [zouzias/spark-lucenerdd#85]
Hi,

I'm running the record linkage example [https://github.com/zouzias/spark-lucenerdd/wiki/Record-Linkage](url) for countries.txt in the cloudera quickstart vm [http://www.cloudera.com/downloads/quickstart_vms/5-8.html](url) and getting some errors.

starting the spark shell with the following for spark 1.6 compatibility:
`spark-shell --packages org.zouzias:spark-lucenerdd_2.10:0.1.0`

first issue is I'm getting the following error as spark starts

```
evicted modules:
	org.scala-lang#scala-reflect;2.10.4 by [org.scala-lang#scala-reflect;2.10.5] in [default]
```

I continue with the example but when I run `val luceneRDD = LuceneRDD(countries)` , I get the following error:
`error: No implicit view available from String => org.apache.lucene.document.Document`

Please can you advise?

Thanks
Dominic

**Comment by zouzias** [comment]
Hi there,

Thank you for trying out `spark-lucenerdd`. You actually need an import for the implicit conversions, i.e.,

```
import org.zouzias.spark.lucenerdd._
```

This will actually put in scope the implicits contained in: https://github.com/zouzias/spark-lucenerdd/blob/v0.1.0/src/main/scala/org/zouzias/spark/lucenerdd/package.scala

Let me know if this solves your problem.

Best,
Anastasios

**Comment by zouzias** [comment]
Speaking of which, you might also want to take a look at https://github.com/zouzias/spark-lucenerdd-examples for more examples.
